#!/usr/bin/env zsh

ZERO="${(%):-%N}"
REPO_DIR="${ZERO%/*}"
source "$REPO_DIR/lib/script_preamble"
source "$REPO_DIR/lib/script_vars"
source "$REPO_DIR/lib/script_functions"

#
# Zparseopts
#

ZKL_PERFORM_WRITE="0"
ZKL_ADD_GIT="0"
ZKL_HELP="0"
ZKL_PATH=""
zparseopts -E -D -A opthash w -write g -git h -help p: -path: || exit 1

# No dry run
(( ${+opthash[-w]} + ${+opthash[--write]} )) && ZKL_PERFORM_WRITE="1"
(( ${+opthash[-g]} + ${+opthash[--git]} )) && ZKL_ADD_GIT="1"
(( ${+opthash[-h]} + ${+opthash[--help]} )) && ZKL_HELP="1"
(( ${+opthash[-p]} )) && ZKL_PATH="${opthash[-p]}"
(( ${+opthash[--path]} )) && ZKL_PATH="${opthash[--path]}"

if [ "$ZKL_HELP" = "1" ]; then
    pinfo "Usage: zekyll-create [options]"
    print "Creates files for given zekylls. If you give zekylls: abcd, it"
    print "will create two files ab--*, cd--*, asking you for a description"
    print "for each of them (they can be given empty). Also, will check for"
    print "correctness of zekylls (no duplicates) and for collisions with"
    print "existing files."
    print
    help-opts
    help-dry
    help-git
    help-path

    exit 0
fi

dry-mode-msg

#
# Read destination path
#

REPLY="$ZKL_PATH"
[ "$REPLY" = "" ] && { read_destination_path || exit 1 }
cd_will_work_on "$REPLY"

#
# Read and examine new zekylls string
#

local zekylls_string_vis=""
while (( 1 )); do
    pinfo "Enter NEW zekylls string:"
    vared -cp "zekylls: " zekylls_string_vis

    print
    zekylls_string="${zekylls_string_vis//_/}"
    pinfo2 "Read: $zekylls_string"
    print

    local -a zekylls1
    zekylls1=( ${(@s:_:)${zekylls_string//(#b)([a-zA-Z0-9][a-zA-Z0-9])/$match[1]_}} )

    pinfo "Checking current zekyll for duplicates..."
    if ! detect_duplicates "${zekylls1[@]}"; then
        perror "Duplicates found, restaring"
        continue
    fi

    print

    #
    # Check for collisions with remaining (uncovered) files
    #

    pinfo "Checking for collisions with remaining files..."

    # Get list of zekylls that are not in zekylls1 list, but exist on filesystem
    # First get all zekylls
    local -a all_zekylls
    all_zekylls=( [a-zA-Z0-9][a-zA-Z0-9]--*(N.) )

    # Here we will have them fully extracted, without paths
    all_zekylls=( "${all_zekylls[@]//(#b)([a-zA-Z0-9])([a-zA-Z0-9])--*/${match[1]}${match[2]}}" )

    # Now check if target zekylls1 have something in common with current files
    local -a common 
    common=( ${all_zekylls:*zekylls1} )

    if [[ "${#common}" -gt 0 ]]; then
        perror "Collisions detected: ${common[@]}, you would create duplicate zekylls, restarting"
        continue
    fi

    break
done

#
# Clear incomplete zekylls
#

if [ "${#${zekylls1[-1]}}" = "1" ]; then
    echo "Removed incomplete zekyll ${zekylls1[-1]}"
    zekylls1[-1]=()
fi

#
# Generate the template files
#

integer count=0
integer all=${#zekylls1}
local zekyll
for zekyll in "${zekylls1[@]}"; do
    count=count+1

    local desc=""
    while (( 1 )); do
        echo "Will create zekyll ${zekyll}--... ($count/$all), enter description"
        vared -cp "description: " desc

        if [[ "$desc" != [a-zA-Z0-9_-]# ]]; then
            perror "Allowed characters are letters, digits, underscore and hyphen, try again"
        else
            break
        fi
    done

    zekyll_file="${zekyll}--${desc}"
    if [ "$ZKL_ADD_GIT" = "1" ]; then
        if [ "$ZKL_PERFORM_WRITE" = "1" ]; then
            touch $zekyll_file; git add $zekyll_file
        else
            echo "touch $zekyll_file; git add $zekyll_file"
        fi
    else
        if [ "$ZKL_PERFORM_WRITE" = "1" ]; then
            touch $zekyll_file
        else
            echo "touch $zekyll_file"
        fi
    fi
done

echo "Your EDITOR string would be: ${EDITOR:-vim} ~/.vimrc" $^zekylls1"--*"

